#!bin/bash

sudo apt install python
sudo apt update && sudo apt upgrade && sudo apt install gcc && sudo apt-get install -y build-essential kernel-package libncurses5-dev bzip2 && sudo apt-get install git ccache automake lzop bison gperf build-essential zip curl zlib1g-dev zlib1g-dev:i386 g++-multilib python-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng
sudo apt-get install manpages-de && sudo apt-get install gcc-arm-linux-gnueabi
sudo apt-get install libssl-dev
sudo apt install gcc
sudo apt-get update
sudo apt-get install gcc-aarch64-linux-gnu
sudo DEBIAN_FRONTEND=noninteractive apt-get install \
          bison build-essential curl flex git gnupg gperf \
          liblz4-tool libncurses5-dev libsdl1.2-dev libxml2 \
          libxml2-utils lzop pngcrush schedtool \
          squashfs-tools xsltproc zip zlib1g-dev \
          build-essential kernel-package libncurses5-dev \
          bzip2 git python expect \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu -y

echo "Almost done"
curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash
echo "done, now trigger build"
